{
  "swagger": "2.0",
  "info":
    {
      "version": "1.0.0",
      "title": "API 文件",
      "description": "API文件",
      "license":
        { "name": "MIT", "url": "https://opensource.org/licenses/MIT" },
    },
  "host": "localhost:10991",
  "basePath": "/",
  "tags": [{ "name": "Users", "description": "API for users in the system" }],
  "schemes": ["http"],
  "consumes": ["application/json"],
  "produces": ["application/json"],
}
